packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/api-key': ^1.5.4
  '@better-auth/drizzle-adapter': ^1.5.4
  '@better-auth/passkey': ^1.5.4
  '@better-upload/client': ^3.0.14
  '@better-upload/server': ^3.0.14
  '@biomejs/biome': ^2.4.6
  '@orpc/client': ^1.13.6
  '@orpc/openapi': ^1.13.6
  '@orpc/server': ^1.13.6
  '@orpc/tanstack-query': ^1.13.6
  '@orpc/zod': ^1.13.6
  '@phosphor-icons/react': ^2.1.10
  '@tailwindcss/postcss': ^4.2.1
  '@tanstack/react-form': ^1.28.4
  '@tanstack/react-query': ^5.90.21
  '@tanstack/react-query-devtools': ^5.91.3
  '@turbo/gen': ^2.8.15
  '@types/node': ^25.4.0
  '@types/nodemailer': ^7.0.11
  babel-plugin-react-compiler: ^1.0.0
  better-auth: ^1.6.9
  dotenv: ^17.2.2
  dotenv-cli: ^7.4.2
  jotai: ^2.19.1
  maplibre-gl: ^5.24.0
  motion: ^12.38.0
  next: 16.2.4
  react: ^19.2.4
  react-day-picker: ^9.14.0
  react-dropzone: ^15.0.0
  tailwindcss: ^4.2.1
  turbo: ^2.9.7
  typescript: ^5
  zod: ^4.1.12

catalogMode: prefer

catalogs:
  react19:
    '@types/react': ^19
    '@types/react-dom': ^19
    react: 19.2.4
    react-dom: 19.2.4

cleanupUnusedCatalogs: true
