import { Geist, Geist_Mono } from "next/font/google";

import "@ziron/ui/globals.css";

import type { Metadata } from "next";

import { cn } from "@ziron/ui/lib/utils";

import { Providers } from "@/components/providers";

const fontSans = Geist({
	subsets: ["latin"],
	variable: "--font-sans",
});

const fontMono = Geist_Mono({
	subsets: ["latin"],
	variable: "--font-mono",
});

export const metadata: Metadata = {
	title: "Admin Portal",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			className={cn("antialiased", fontMono.variable, "font-sans", fontSans.variable)}
			lang="en"
			suppressHydrationWarning
		>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
